### ISSUE TITLE
如何连接服务端？

### ISSUE THREAD

**Issue by robinfoxnan** [tinode/tindroid#136]
服务端已经配置成功了，使用openssl生成证书，
"tls": {
		// Enable TLS.
		"enabled": true,
		"http_redirect": ":443",

		"cert_file": "/root/certs/cert.crt",
		"key_file": "/root/certs/private.key"
	},
并且使用客户端也能访问了，https://ip:6060
我没有找到安卓编译好的发布版，自己试着编译了一个，
连接时候服务器设置了ip地址，
但是一直报错，说无法解析Tls header,
服务端一直说：
http: TLS handshake error from 114.249.197.53:30551: remote error: tls: unknown certificate
这个问题是哪里配置有问题么？

**Comment by or-else** [comment]
> The server has been configured successfully, using openssl to generate a certificate,
> "tls": {
> //Enable TLS.
> "enabled": true,
> "http_redirect": ":443",
> 
> "cert_file": "/root/certs/cert.crt",
> 
> "key_file": "/root/certs/private.key"
> 
> },
> 
> And you can also access it using the client, https://ip:6060
I didn't find a compiled release version for Android, so I tried to compile one myself.
When connecting, the server sets the ip address.
But it keeps reporting an error, saying that the Tls header cannot be parsed,
The server keeps saying:
http: TLS handshake error from 114.249.197.53:30551: remote error: tls: unknown certificate
Is there a problem with this configuration?

I guess, the problem is due to a mismatch between the name of the domain in the certificate and the actual domain you re serving from. Anyway, I don't believe the problem has anything to do with Tinode. It's rather a generic TLC config problem.
