### ISSUE TITLE
Empty chat list on cold start

### ISSUE THREAD

**Issue by mohgh** [tinode/tindroid#33]
I think there's a bug in `ContactsActivity` on line 107 (devel branch) that causes the list to not be updated. This line should be as following:
`Fragment fragment = fm.findFragmentByTag(FRAGMENT_CHAT_LIST);`

**Comment by or-else** [comment]
Please describe the problem in more details: the solution is certainly not a valid one because 
https://github.com/tinode/tindroid/blob/devel/app/src/main/java/co/tinode/tindroid/ContactsActivity.java#L113
calls
https://github.com/tinode/tindroid/blob/devel/app/src/main/java/co/tinode/tindroid/ContactsFragment.java#L90
which in turn calls
https://github.com/tinode/tindroid/blob/devel/app/src/main/java/co/tinode/tindroid/ChatListFragment.java#L366

**Comment by mohgh** [comment]
Yes, you're right. Sorry.
I've customized your app so that instead of tabs I only show `ChatListFragment` in `ContactsActivity`. So ContactsFragment is null and `chatDatasetChanged` won't be called. I should find a workaround for my problem.
