### ISSUE TITLE
Access to topic tags in MessageAcitivity

### ISSUE THREAD

**Issue by mohgh** [tinode/tindroid#34]
Is it possible to have access to the topic tags in `MessageActivity`? The `tags` field of the `topic` object is null. I'm using a specific tag in some topics and I need this feature to detect the tag.

**Comment by or-else** [comment]
That field is null because it's only available in topics where the current user is the owner and only when requested. 

Please describe your use case. It seems like you want to use tags for a purpose they were not intended to be used for.

Take a look at `private`. You may store whatever you want there.

**Comment by or-else** [comment]
By the way, take a look at https://github.com/tinode/tindroid/tree/find. I'm currently refactoring the app to incorporate search by tags.

**Comment by mohgh** [comment]
Thanks. I'm using `private` field for my purpose now.
