### ISSUE TITLE
On the sorting of SQLite

### ISSUE THREAD

**Issue by abitcyanine** [tinode/tindroid#68]
I use the web client to send text messages 50 times continuously. After the Android client receives the message, they are loaded on the view and a display order error occurs. 
the right order：
0，1，2，3，4，5，6，7，8，9，0，1，2，3，4，5，6，7，8，9，0
but the actual order：
0，3，2，1，6，5，4，7，8，9，0，1，2，3，4，5，6，7，8，9，0
I checked the database file of tindroid and query code and found that the query order was ts desc. The problematic data have the same ts and sqlite doesn't process data at the same ts correctly.

touched | seqid | content
1575592766672|419||9
1575592765504|418||8
1575592765184|417||7
1575592764922|414||4
1575592764922|415||5
1575592764922|416||6
1575592763925|411||1
1575592763925|412||2
1575592763925|413||3

I fixed the tindroid query, add order by _id desc.

**Comment by or-else** [comment]
The reason why it sorting by timestamp is because of deferred messages. You probably should not sort by `_id` either. The correct order is sorting by `seq` but then deferred messages have to be handled explicitly.

**Comment by or-else** [comment]
It would be interesting to see the log. The `seq` order should be the same as `ts` order.

**Comment by or-else** [comment]
Actually, it's even simpler. In your case `ts` is the same for many messages. It would be enough (and correct) to make the sort order `ts DESD, seq DESC`. I'll make that change. Thanks!

**Comment by abitcyanine** [comment]
Thank you for your reply.
If the order of message sorting depends on ts and seq, it can solve the problem of message order sent by other users. However, if the messages sent by oneself are added between the received messages of same ts, I think there may be bugs in ui display, because the seq value of the messages sent by oneself is uncertain.

**Comment by abitcyanine** [comment]
In another case, if the sender needs to send a large attachment, after the message is actually sent, the ts value will be updated and cause the message position changed in ui view. For instance:
original order  -> msg1, msg2, msg you sent, msg3       
ts updated ->   msg1, msg2, msg3, msg you sent          
I think the former should appear at the sender and the latter at the receiver. That's why I thought of using _id as the sort basis

**Comment by or-else** [comment]
I think the key principle of a conversation is that all participants see the same conversation flow. I.e. all participants see messages in the same order and that order reflects the actual order of message appearance. Otherwise abuse and confusion is possible.

The message order is defined by the server. It ensures that the messages are sent to all participants in the same order. Until the message is received by the server its position in the order is not defined. That means no matter what logic you use on the client for positioning unsent messages, it may change once the message is received by the server. 

In case of a large upload the message is not sent until the upload is completed. Consequently, the message may be re-positioned once the upload is completed and the message is received by the server.

I do believe that all clients should see the same order of messages.

**Comment by abitcyanine** [comment]
ok, I understand your design.
